run:
  skip-files:
    - "tests/k8s_utils.go"
    - "tests/hook_types.go"
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
    ## No function should take more than 5 arguments
    - name: argument-limit
      severity: warning
      arguments:
      - 6
